version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - ELASTIC_HOST=elastic-stack-elasticsearch-1
    restart: always

networks:
  elk:
    external: true